### ISSUE TITLE
[BUG]1.16.5 with enigmaticlegacy:cursed_ring

### ISSUE THREAD

**Issue by 2929762171** [ochotonida/trofers#13]
Loot_table:
![image](https://github.com/ochotonida/trofers/assets/98941945/e6c44e80-7e85-4f00-84e3-5e5f6eaaea64)

Before:
![image](https://github.com/ochotonida/trofers/assets/98941945/5d840029-689a-4db6-b917-77c225f70e1c)

After:
![image](https://github.com/ochotonida/trofers/assets/98941945/6a31373f-baa6-4ae7-af4e-7c6c1ac66d69)
![image](https://github.com/ochotonida/trofers/assets/98941945/ef4785e0-9d76-4736-84f1-3542fd66bdd4)

The reward will be changed to the trophy itself.
Happens on any trophy with a 'lootTable' set.

**Comment by ochotonida** [comment]
I'm assuming the cursed ring is an item that gives you silk touch or affects block drops in some way? Looks like a loot modifier thinks the block is being broken when it's not. I'll look into this when I have a bit more time.

**Comment by 2929762171** [comment]
![image](https://github.com/ochotonida/trofers/assets/98941945/fea178c4-221b-460e-b63c-30a5a6a6c17f)

**Comment by ochotonida** [comment]
Hmm, that's odd, I'm not sure why it would be causing an issue like this. Does this happen with any other curios from Enigmatic Legacy?
You might want to report this issue on Enigmatic Legacy's issue tracker as well if you haven't already.

**Comment by ochotonida** [comment]
I'm not entirely sure what Enigmatic Legacy might be doing on their end to cause something like this, but I've uploaded a new version with a workaround that seems to fix the issue.
