### ISSUE TITLE
[BUG] New Mutant More Mod mobs are shaking in Trofers 1.19.2 - 3.2.0

### ISSUE THREAD

**Issue by ArcaneAlloy** [ochotonida/trofers#15]
https://github.com/ochotonida/trofers/assets/110386565/56df9f4a-5237-4f7d-8cb0-70842a43d2e6

As you can see in this video the mobs from the New Mutant More mod https://www.curseforge.com/minecraft/mc-mods/new-mutant-more are shaking when they are placed in a Trophy.

This is the code of the Datapack for one of this entities:
`{
  "colors": {
    "accent": "#606060",
    "base": "#606060"
  },
  "conditions": [
    {
      "type": "forge:mod_loaded",
      "modid": "mutantmore"
    }
  ],
  "display": {
    "scale": 0.4
  },
  "effects": {
    "rewards": {
      "cooldown": 9600,
      "lootTable": "trofers:trophies/mutant_wither_skeleton"
    },
    "sound": {
      "soundEvent": "mutantmore:entity.mutant_wither_skeleton.roar"
    }
  },
  "entity": {
    "type": "mutantmore:mutant_wither_skeleton"
  },
  "name": {
    "color": "#20FCCE",
    "translate": "trophy.trofers.composed",
    "with": [
      {
        "translate": "entity.mutant_wither_skeleton"
      }
    ]
  }
}`

This can be solved in some way? 

Thanks!

**Comment by ochotonida** [comment]
I'm afraid that this is an issue with how GeckoLib renders entities, most mods that use GeckoLib have similar problems. While I believe this is no longer an issue in 1.20.1, I don't think there's a way around this in 1.19.2. It's definitely not something I can fix on my end.
