### ISSUE TITLE
Crash w/ Googly Eyes Mod

### ISSUE THREAD

**Issue by WenXin20** [ochotonida/trofers#2]
`Minecraft v1.16.5`
`Forge v36.2.4`
`Trofers v2.0.0`
[`Googly Eyes v10.4.0`](https://www.curseforge.com/minecraft/mc-mods/googlyeyes)

If a trofer renders a mob with googly eyes either in the gui or after a trofer has been placed, the game will immediately crash. This can be easily reproduced by entering the config for googly eyes and setting the `googly_eye_chance` to 100.
[Crash Report](https://gist.github.com/WenXin20/d11ca97cdb4da3998fd0604cde2149c5)

**Comment by ochotonida** [comment]
Thanks for the report, the issue should be fixed in the next update

**Comment by WenXin20** [comment]
Thanks!
