### ISSUE TITLE
mod failed to load 1.18.2

### ISSUE THREAD

**Issue by Halibear** [ochotonida/trofers#8]
Getting mod failed to load: Caused by 0: java.lang.reflect.InvocationTargetException

when using:
trofers-1.18.1-2.6.0
forge-1.18.2-40.0.19

[crash-2022-03-19_12.16.14-fml.txt](https://github.com/ochotonida/trofers/files/8309956/crash-2022-03-19_12.16.14-fml.txt)

**Comment by Halibear** [comment]
[debug.log](https://github.com/ochotonida/trofers/files/8309961/debug.log)
[latest.log](https://github.com/ochotonida/trofers/files/8309962/latest.log)

**Comment by ochotonida** [comment]
Thanks for the report! This is caused by a breaking change Forge made in 40.0.18. I've uploaded a patch that fixes the issue, which should be available for download soon.
