### ISSUE TITLE
[Suggestion] Alternate methods for obtaining trophies

### ISSUE THREAD

**Issue by DoctorWafflePhD** [ochotonida/trofers#9]
While trophies being rare drops from mobs works well for most hostile mobs, other mobs are quite unlikely to ever be seen as trophies, usually passive mobs that players aren't really incentivized to kill.

To alleviate this, there could possibly be other methods that trophies could be obtained, manageable by config. If possible, these could even be supported by datapacks, i.e. listing an event that could cause a trophy to spawn.

Config options could include whether alternate methods are enabled, and whether they should have a different chance for spawning trophies.

Some alternate methods to obtain trophies could include the following:
- Breeding mobs
- Taming mobs
- Building mobs (Iron Golem)
- Fishing (Cod, Salmon, Pufferfish, Tropical Fish)
- Trading with mobs (Villagers, Piglins)
- Other unique mob behaviors (i.e. saving beached whales in Alex's Mobs, feeding Tazmanian Devils from Alex's Mobs Rotten Flesh, harvesting ores from Quark's Toretoises, etc.)

**Comment by ochotonida** [comment]
While I agree that acquiring some trophies can be a bit of a problem, I'm honestly not sure whether I want to do something about it. I'd need a lot of custom behavior for entities that work in all kinds of different ways. There's trophies for over 150 entities already, and I'll probably be adding even more in the future. Things would quickly become an unmaintainable mess, as I'd have to spend a significant of time fixing things every time mods update their entities or when new Minecraft versions come out.

Even if I manage to keep things relatively simple, balancing many different methods for obtaining trophies such that they drop with more or less the same rate would still be very difficult and time-consuming.

In general I just think it's a bit beyond the scope of the mod.
